### ISSUE TITLE
raft: lead 节点复制日志

### ISSUE THREAD

**Issue by junxfl** [ipdcode/raft#5]
请问一下，我阅读raft的源码。lead节点通过ReqMsgAppend消息向follow节点同步日志数据时，没有等待follow节点的响应，就向客户端返回ack了，raft协议不是要求lead节点需要等待大多数follow节点的响应以确保大多数follow节点同步数据成功才能向客户端返回ack吗？

**Comment by byteink** [comment]
@junxfl  是有等的，只不过不是同步等待。follower收到ReqMsgAppend消息后会回应一个RespMsgAppend 消息给leader，leader收到后判断对应位置的日志是否复制成功。

**Comment by junxfl** [comment]
好的，非常感谢，我再看下代码。

**Comment by byteink** [comment]
@junxfl 不客气:) 具体可以看看raft_fsm_leader.go文件stepLeader函数里对RespMsgAppend消息的处理。leader保存各个副本的复制进度（raft_replica.go），当判断大多数副本的进度大于等于了 index i，就更新commit位置到index i。给客户端回应是日志commit并apply后才进行的。
